import { Platform, View } from 'react-native';
export const staticText = {
  // App branding
  app: {
    name: 'Renzi',
    tagline: 'Welcome to Luxury Living',
    description: 'Premium Luxury Real Estate Platform',
    version: 'v1.0.0',
  },
  // Authentication
  auth: {
    signIn: 'Sign In',
    signUp: 'Create Account',
    signOut: 'Sign Out',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome back',
    joinRentziLux: 'Join RentziLux',
    termsAndConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    acceptTerms: 'I accept the Terms & Conditions and Privacy Policy',
    quickDemoAccess: 'Quick Demo Access',
    loginSuccessful: 'Login successful! Welcome to RentziLux',
    registrationSuccessful: 'Registration successful! Please verify your account',
  },
  // User roles
  roles: {
    renter: 'Renter',
    investor: 'Investor',
    homeowner: 'Homeowner',
    descriptions: {
      renter: 'Discover and book luxury properties',
      investor: 'Invest in premium real estate opportunities',
      homeowner: 'List and manage your luxury properties',
    },
  },
  // Navigation
  navigation: {
    dashboard: 'Dashboard',
    discover: 'Discover',
    search: 'Search',
    portfolio: 'Portfolio',
    profile: 'Profile',
    settings: 'Settings',
    notifications: 'Notifications',
    bookings: 'Bookings',
    properties: 'Properties',
    investments: 'Investments',
  },
  // Common actions
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    book: 'Book Now',
    invest: 'Invest',
    contact: 'Contact',
    share: 'Share',
    favorite: 'Add to Favorites',
    filter: 'Filter',
    sort: 'Sort',
    search: 'Search',
    apply: 'Apply',
    reset: 'Reset',
    confirm: 'Confirm',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
    submit: 'Submit',
    update: 'Update',
    upload: 'Upload',
    download: 'Download',
  },
  // Status messages
  status: {
    loading: 'Loading...',
    success: 'Success!',
    error: 'Something went wrong',
    noData: 'No data available',
    noResults: 'No results found',
    tryAgain: 'Please try again',
    comingSoon: 'Coming soon!',
    underMaintenance: 'Under maintenance',
    offline: "You're offline",
    connected: 'Connected',
  },
  // Property related
  property: {
    featured: 'Featured Properties',
    luxury: 'Luxury Properties',
    premium: 'Premium Collection',
    exclusive: 'Exclusive Listings',
    newListings: 'New Listings',
    trending: 'Trending Now',
    recommended: 'Recommended for You',
    nearYou: 'Near You',
    priceRange: 'Price Range',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    amenities: 'Amenities',
    location: 'Location',
    availability: 'Availability',
    bookingStatus: {
      available: 'Available',
      booked: 'Booked',
      pending: 'Pending',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
    },
  },
  // Investment related
  investment: {
    portfolio: 'Investment Portfolio',
    totalValue: 'Total Portfolio Value',
    roi: 'Return on Investment',
    properties: 'Properties',
    performance: 'Performance',
    analytics: 'Analytics',
    opportunities: 'Investment Opportunities',
    riskLevel: 'Risk Level',
    expectedReturn: 'Expected Return',
    minimumInvestment: 'Minimum Investment',
  },
  // Support and help
  support: {
    helpCenter: 'Help Center',
    contactSupport: 'Contact Support',
    faq: 'Frequently Asked Questions',
    documentation: 'Documentation',
    tutorials: 'Tutorials',
    feedback: 'Send Feedback',
    reportIssue: 'Report an Issue',
    concierge: 'Luxury Concierge',
    available24_7: 'Available 24/7',
    premiumSupport: 'Premium Support',
  },
  // Luxury specific messaging
  luxury: {
    exclusive: 'Exclusive',
    premium: 'Premium',
    luxury: 'Luxury',
    elite: 'Elite',
    prestige: 'Prestige',
    sophisticated: 'Sophisticated',
    elegant: 'Elegant',
    refined: 'Refined',
    opulent: 'Opulent',
    magnificent: 'Magnificent',
    exceptional: 'Exceptional',
    extraordinary: 'Extraordinary',
    worldClass: 'World-Class',
    bespoke: 'Bespoke',
    curated: 'Curated',
  },
  // Error messages
  errors: {
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordComplexity: 'Password must contain uppercase, lowercase, number, and special character',
    passwordMismatch: 'Passwords do not match',
    otpExpired: 'OTP expired. Request new.',
    otpIncorrect: 'Incorrect OTP entered.',
    otpMaxAttempts: 'Maximum resend attempts reached.',
    otpInvalid: 'Please enter a valid 6-digit OTP',
    networkError: 'Network error. Please check your connection',
    serverError: 'Server error. Please try again later',
    unauthorized: 'Unauthorized access',
    forbidden: 'Access forbidden',
    notFound: 'Resource not found',
    validationError: 'Validation error',
  },
  // OTP related
  otp: {
    title: 'Verify Your Account',
    subtitle: "We've sent a 6-digit code to your email and phone",
    enterCode: 'Enter 6-Digit Code',
    codeExpires: 'Code expires in',
    codeExpired: 'Code expired',
    didntReceive: "Didn't receive the code?",
    resendCode: 'Resend Code',
    verifyCode: 'Verify Code',
    otpSent: 'OTP sent successfully!',
    verificationSuccessful: 'Verification successful!',
    maxAttemptsReached: 'Maximum attempts reached. Please try again later.',
    resendCooldown: 'Please wait before requesting another code',
  },
  // Success messages
  success: {
    accountCreated: 'Account created successfully',
    profileUpdated: 'Profile updated successfully',
    passwordChanged: 'Password changed successfully',
    bookingConfirmed: 'Booking confirmed successfully',
    investmentCompleted: 'Investment completed successfully',
    propertyListed: 'Property listed successfully',
    messagesSent: 'Message sent successfully',
    settingsSaved: 'Settings saved successfully',
  },
};