import React from 'react';
import { Link, Stack, usePathname } from 'expo-router';
import { StyleSheet, View, Text, Dimensions } from 'react-native';

export default function NotFoundScreen() {
  const pathname = usePathname();
  
  return (
    <>
      <Stack.Screen options={{ title: 'Page Not Found' }} />
      <View style={styles.container}>
        <View style={styles.iconContainer}>
          <Text style={styles.icon}>🔍</Text>
        </View>
        
        <Text style={styles.title}>404</Text>
        <Text style={styles.subtitle}>Page Not Found</Text>
        
        <View style={styles.messageContainer}>
          <Text style={styles.description}>
            Oops! The screen you're looking for doesn't exist.
          </Text>
          <Text style={styles.routeText}>
            Route: <Text style={styles.routeHighlight}>{pathname}</Text>
          </Text>
          <Text style={styles.llmNote}>
            📝 This screen wasn't generated by LLM. If you wish, ask it to generate the "{pathname}" route.
          </Text>
        </View>

        <Link href="/" style={styles.homeButton}>
          <View style={styles.buttonContainer}>
            <Text style={styles.buttonText}>🏠 Go to Home</Text>
          </View>
        </Link>
      </View>
    </>
  );
}

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#f8fafc',
  },
  iconContainer: {
    marginBottom: 20,
  },
  icon: {
    fontSize: 64,
    opacity: 0.7,
  },
  title: {
    fontSize: 72,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 32,
    textAlign: 'center',
  },
  messageContainer: {
    maxWidth: width * 0.8,
    marginBottom: 40,
  },
  description: {
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 16,
  },
  routeText: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 8,
  },
  routeHighlight: {
    fontWeight: 'bold',
    color: '#1e293b',
    fontFamily: 'monospace',
  },
  llmNote: {
    fontSize: 14,
    color: '#059669',
    textAlign: 'center',
    fontStyle: 'italic',
    backgroundColor: '#ecfdf5',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
  },
  homeButton: {
    marginBottom: 32,
  },
  buttonContainer: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  footer: {
    maxWidth: width * 0.7,
  },
  footerText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 20,
  },
});
    